# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='a link to the prior art')),
                ('text', models.TextField(blank=True, help_text='additional detail', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Filed'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('joke', models.ForeignKey(help_text='The joke this claim is in regards to', on_delete=django.db.models.deletion.CASCADE, to='jokes.Joke')),
            ],
            options={
                'ordering': ('-created', '-updated'),
            },
        ),
    ]
