# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_joke_approved'),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='joke',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='link',
        ),
        migrations.AddField(
            model_name='claim',
            name='infringed_joke',
            field=models.ForeignKey(default=1, help_text='The original joke', on_delete=django.db.models.deletion.CASCADE, related_name='infringed_claim', to='jokes.Joke'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='infringing_joke',
            field=models.ForeignKey(default=1, help_text='The infringing joke', on_delete=django.db.models.deletion.CASCADE, related_name='infringing_claim', to='jokes.Joke'),
            preserve_default=False,
        ),
    ]
