# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='original',
            new_name='parent',
        ),
    ]
