# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_auto_20160101_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
